[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[project]
name = "openg2p-ioc-common"
authors = [
  { name="OpenG2P", email="info@openg2p.org" },
]
description = "OpenG2P Library for initializing common IOC aspects"
readme = "README.md"
requires-python = ">=3.7"
license = "MPL-2.0"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Operating System :: OS Independent",
]
dependencies = [
  "pydantic-settings >=2.0.0",
  "asyncio >=3.4.3",
  "httpx >=0.28.1",
  "orjson >=3.9.7",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://openg2p.org"
Documentation = "https://docs.openg2p.org/"
Repository = "https://github.com/openg2p/openg2p-fastapi-common"
Source = "https://github.com/openg2p/openg2p-fastapi-common"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit]
default-version = "0.0.0+unknown"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{branch}.{vcs}{rev}"
distance-dirty = "{next_version}.dev{distance}+{branch}.{vcs}{rev}.dirty"

[tool.versioningit.next-version]
method = "smallest"
