name: Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution Common
      run: python -m build ./openg2p-fastapi-common
    - name: Build distribution Auth
      run: python -m build ./openg2p-fastapi-auth
    - name: Publish Common
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: openg2p-fastapi-common/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish Auth
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: openg2p-fastapi-auth/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish common-g2pconnect-id-mapper
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: openg2p-common-g2pconnect-id-mapper/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
